//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Entidades : DbContext
{
    public Entidades()
        : base("name=Entidades")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Amortizacion_pro> Amortizacion_pro { get; set; }
    public virtual DbSet<Proyecto> Proyecto { get; set; }
    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    public virtual DbSet<Amortizacion_cat> Amortizacion_cat { get; set; }
    public virtual DbSet<Costos_cat> Costos_cat { get; set; }
    public virtual DbSet<Costos_Pro> Costos_Pro { get; set; }
    public virtual DbSet<FNE> FNE { get; set; }
}
